### ISSUE TITLE
Testing small gene sets with blitzgsea 

### ISSUE THREAD

**Issue by dinithins** [MaayanLab/blitzgsea#4]
Hello. 
This is a cool package! I want to try this out for a smaller set of genes (ranging from a size of 100 to 1000s) yet it seems the current version does not support this. I get a "ValueError: Sample larger than population or is negative" when I tried any list of genes of size less than 4000. I suppose this is due to the line: 
`x = sorted(list(set(np.append([1,4,6, np.max(ll), 2000, 4000], nn).astype("int"))))` (line 91) in __init__.py. 
Is there a way for blitzgsea to work with smaller sets of genes? 
Many thanks in advance.

Dinithi

**Comment by abearab** [comment]
Same here!

**Comment by lachmann12** [comment]
I hope in the current version it is fixed. The old code assumed at least 4000 genes in a signature.

**Comment by alexlenail** [comment]
I am still getting this error with `blitzgsea-1.2.10` installed today.
